### PR TITLE
migrate to rancher2

### PR DESCRIPTION
**Pull request by drpebcak**
Some hygiene changes, plus changes to logrotate container for k8s

### CODE REVIEW

**Comment by drpebcak** [comment]
@cloudnautique take a look at this.

**Comment by cloudnautique** [comment]
So far it makes sense. I would like to see a drone file for building all the images and publishing.

**Comment by drpebcak** [comment]
@cloudnautique just added a drone config. Can you enable this repo in pr/publish?

**Comment by drpebcak** [comment]
@cloudnautique looks like this is passing now. Can you merge and tag a `v0.1.0` release?

**Pull request merged**
